NAVBAR_HOME_LINK_XPATH = '//*[@id="__next"]/div/div[1]/div[1]/div/div/nav/div[2]/a[3]'
NAVBAR_BLOG_POSTS_LINK_XPATH = '//*[@id="__next"]/div/div[1]/div[1]/div/div/nav/div[2]/a[2]'
NAVBAR_ABOUT_ME_LINK_XPATH = '//*[@id="__next"]/div/div[1]/div[1]/div/div/nav/div[2]/a[1]'
NAVBAR_LOGO_LINK_XPATH = '//*[@id="__next"]/div/div[1]/div[1]/div/div/nav/div[1]/div/a'
NAVBAR_SEARCH_LINK_XPATH = '//*[@id="search-input"]'

HOMEPAGE_MAIN_PIC_XPATH = '//*[@id="__next"]/div/div[1]/div[2]/span/img'
HOMEPAGE_ALL_BLOG_POSTS_BUTTON_XPATH = '//*[@id="__next"]/div/div[1]/div[1]/main/div/div/div[1]/a'
HOMEPAGE_BLOG_POSTS_CATEGORIES_BUTTON_XPATH = '//*[@id="__next"]/div/div[1]/div[1]/main/div/div/div[2]/a'
HOMEPAGE_SEE_ALL_LINK_XPATH = '//*[@id="__next"]/div/div[2]/h2/a'
HOMEPAGE_BLOGS_DIV_ELE_XPATH = '//*[@id="__next"]/div/div[2]/div'
HOMEPAGE_EXPLORE_MORE_BLOGS_XPATH = '//*[@id="__next"]/div/div[2]/div[2]/h2'
HOMEPAGE_DISCOVER_ARTICLES_BUTTON_XPATH = '//*[@id="__next"]/div/div[2]/div[2]/a'

FOOTER_ABOUT_ME_LINK_XPATH = '//*[@id="__next"]/footer/div/nav/div[1]/a'
FOOTER_BLOG_POSTS_LINK_XPATH = '//*[@id="__next"]/footer/div/nav/div[2]/a'
FOOTER_HOME_LINK_XPATH = '//*[@id="__next"]/footer/div/nav/div[3]/a'
FOOTER_CR_KAZI_XPATH = '//*[@id="__next"]/footer/div/p/span/a'
FOOTER_CR_YEAR_XPATH = '//*[@id="__next"]/footer/div/p/span'
FOOTER_LINKEDIN_SVG_XPATH = '//*[@id="__next"]/footer/div/div/a[1]'
FOOTER_TWITTER_SVG_XPATH = '//*[@id="__next"]/footer/div/div/a[2]'
FOOTER_GITHUB_SVG_XPATH = '//*[@id="__next"]/footer/div/div/a[3]'
