name: Run Linter

on:
  pull_request:

jobs:
  RunBuildCheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: |
          npm ci
  
      - name: Run Lint
        run: |
            npm run lint
